using Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace StructureBlockImporter
{
    public class ImportStructure : CustomCommand
    {
        private static WebClient _client = new WebClient();

        public override String Command => "importstructure";

        public override String[] Usage { get; }

        public ImportStructure()
        {
            Usage = new string[]
            {
                Command + " file <Source Path>",
                Command + " download <Source URL> <Target Name>"
            };
        }

        public override void Handle(String[] args)
        {
            var packFilePath = World.WorldPath + @"datapacks\imported\pack.mcmeta";
            switch (args[0])
            {
                case "file":
                    var path = args[1];
                    var p = World.WorldPath + @"datapacks\imported\data\imported\structures\";
                    if (!Directory.Exists(p))
                    {
                        Directory.CreateDirectory(p);
                        if (!File.Exists(packFilePath))
                        using (var v = File.CreateText(packFilePath))
                        {
                            v.WriteLine("{");
                            v.WriteLine("\"pack\": {");
                            v.WriteLine("\"pack_format\": 1,");
                            v.WriteLine("\"description\": \"Generated by the Structure Block Importer Plugin. Containing Structures and such\"");
                            v.WriteLine("}");
                            v.WriteLine("}");
                        }
                    }
                    File.Copy(path, p + Path.GetFileName(path));
                    break;
                case "download":
                    var targetPath = World.WorldPath + @"datapacks\imported\data\imported\structures\";

                    if (!Directory.Exists(targetPath))
                    {
                        Directory.CreateDirectory(targetPath);

                        if (!File.Exists(packFilePath))
                            using (var v = File.CreateText(packFilePath))
                            {
                                v.WriteLine("{");
                                v.WriteLine("\"pack\": {");
                                v.WriteLine("\"pack_format\": 1,");
                                v.WriteLine("\"description\": \"Generated by the Structure Block Importer Plugin. Containing Structures and such\"");
                                v.WriteLine("}");
                                v.WriteLine("}");
                            }
                    }

                    _client.DownloadFile(args[1], targetPath + (args[2].EndsWith(".nbt") ? args[2] : (args[2] + ".nbt")));
                    break;
            }
        }
    }
}
